### ISSUE TITLE
Result cannot be piped

### ISSUE THREAD

**Issue by ukutaht** [felipesere/selecta#16]
Currently the result of `selecta` cannot be piped to the next process:

``` bash
$ ls | target/selecta | echo

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError { kind: OtherIoError, desc: "stream is not a tty", detail: None }', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:743
```

It panics because of [this](https://github.com/felipesere/selecta/blob/master/src/tty.rs#L75) line: The window size is pulled from the raw stdout which in this case is not the terminal.

@rschmitt has solved it [here](https://github.com/rschmitt/heatseeker/blob/master/src/screen/unix.rs#L184) by calling `ioctl`.

**Comment by felipesere** [comment]
Closed with #19
