### ISSUE TITLE
Consider using rustbox

### ISSUE THREAD

**Issue by Stebalien** [felipesere/selecta#28]
Instead of manually managing input/output, consider using rustbox. This will:
1. Take over the entire entire terminal when matching and return the screen to its previous state on exit (like `fzf`).
2. Make it easier to handle special keys (like up, down, etc.) fixing #3, #27.

This will probably fix #26 as well.

**Comment by ukutaht** [comment]
The worry I have is exactly the fact that it takes over the entire terminal. The main use case for me is using it inside Vim as seen in the screenshot. I wonder if we could use it and preserve the current behaviour where we only draw a part of the screen. I'm not familiar with termbox, so any insights would be helpful.

![screen shot 2015-02-24 at 09 54 49](https://cloud.githubusercontent.com/assets/3731516/6346868/3b934fca-bc0b-11e4-917d-530e114069f6.png)

**Comment by Stebalien** [comment]
Termbox takes over the entire screen so if you only want to modify part of the screen, you'll have to do it yourself.

**Comment by Stebalien** [comment]
Out of curiosity, how are you getting this to work with vim?

**Comment by rschmitt** [comment]
It works with Vim using the ordinary Vimscript that you can find in the Selecta readme. Note that this does _not_ work with Neovim, because of the way it takes over the terminal: https://github.com/neovim/neovim/issues/1044
